name: 'AutoRelease'
description: 'Automatically publishes a new release'
inputs:
  UserName: 
    description:  'Your GitHub UserName'
    required: true
  Repository: 
    description:  'The name of the GitHub repository that will be released'
    required: true
  GHToken: 
    description:  'Your GitHub token'
    required: true
outputs:
  message:
    description: "Information message"
    value: "${{ steps.autorelease.outputs.message }}"
runs:
  using: "composite"
   env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  steps:
    - id: autorelease
      run: ${{ github.action_path }}/draftAndDeployRelease.ps1 -username ${{ inputs.username }} -repository ${{ inputs.repository }} -ghtoken ${{ secrets.GITHUB_TOKEN }} 
      shell: pwsh
